#!/bin/bash

[ -e $HOME/.env ] && . $HOME/.env/fun

presence()
{
    $1 --help &>/dev/null
    [ $? -gt 0 ] && die "Please install $1."
}

for s in 'git' 'curl' 'zsh'; do presence $s; done

[ ! -e $HOME/.env ] && git clone https://github.com/redpfire/env $HOME/.env \
                   && echo "+ Continuing from disk" \
                   && exec $HOME/.env/install

if [ "$1" = "update" ]; then
    run-parts $HOME/.env/hooks/update
elif [ -n "`find $HOME/.env/hooks -name \"$1\"`" ]; then
    hook $1
else
    run-parts $HOME/.env/hooks
    echo "+ All done."
fi
