#!/bin/sh

hc() {
    herbstclient "$@"
}

hc emit_hook reload

Mod=Mod4

hc keybind $Mod-Return spawn xst -c 'xst' & transset-df 0.86 -n xst
hc keybind $Mod-r spawn dmenu_run -fn 'Iosevka Custom:pixelsize=12:antialias=true:autohint=true' -nb '#000000' -nf '#ffffff' -sb '#ffffff' -sf '#000000'

hc keybind $Mod-Control-q close
hc keybind $Mod-Control-x quit
hc keybind $Mod-Control-r reload

hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right 0.5
hc keybind $Mod-Shift-r remove

hc keybind $Mod-Tab cycle_layout -1

tag_names=('www' 'term' 'disc' 'misc' 'misc2' 'obs')
tag_layouts=('max' 'horizontal' 'max' 'grid' 'grid' 'max')
tag_keys=('a' 's' 'd' 'f' 'z' 'x')

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    hc use "${tag_names[$i]}"
    hc set_layout "${tag_layouts[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc use "${tag_names[0]}"

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-g set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-g floating toggle
hc keybind $Mod-t pseudotile toggle

hc keybind $Mod-Ctrl-k resize up
hc keybind $Mod-Ctrl-j resize down

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1

hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set focus_follows_mouse 1

bg1="#303030"
bg2="#606060"
hc attr theme.active.color "$bg2"
hc attr theme.normal.color "$bg1"
hc attr theme.urgent.color orange
hc attr theme.floating.outer_color "$bg1"
hc attr theme.active.inner_color "$bg2"
hc attr theme.active.outer_color "$bg2"
# hc attr theme.background_color "#333333"

hc unrule -F
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc unlock

xrdb ~/.Xresources
# setxkbmap pl -option caps:super
# xsetroot -cursor_name ptr_left

# # key repeat rate
# xset r rate 200 30

# # set tapping on touchpad
# xinput set-prop 16 315 1
# xbindkeys
dunst &
picom -b --inactive-dim 0 --inactive-opacity-override -i 0.9 --mark-ovredir-focused

panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh

for monitor in $(hc list_monitors | cut -d: -f1); do
    "$panel" "$monitor" &
done
