#!/bin/sh

n=`basename $0`

case "$1" in
    "dev")
        shift;
        case "$1" in
            "start")
                ssh -t kup "sudo qm start 101"
            ;;
            "stop")
                ssh -t kup "sudo qm stop 101"
            ;;
            *)
                echo -e "$n dev start\n$n dev stop"
            ;;
        esac
    ;;
    *)
        echo -e "$n\n\tdev"
    ;;
esac
