#!/bin/env python3
import curses, random, time
from time import sleep
from datetime import datetime

start = datetime.now().replace(microsecond=0)

stdscr = curses.initscr()
curses.start_color()

curses.init_pair(2, curses.COLOR_BLUE, curses.COLOR_BLACK)

curses.noecho()
curses.cbreak()
stdscr.clear()
stdscr.nodelay(True)
curses.curs_set(False)
dim = stdscr.getmaxyx()

droplets = []
for x in range(0 - dim[0]+3, dim[1]-3):
    if (x % 3) == 0 or x < 0:
        if x >= 0:
            droplets.append([x, 0])
        elif (abs(x) % 3) == 0:
            droplets.append([0, abs(x)])
current = []

while True:
    c = stdscr.getch()
    if c == ord('q'):
        break

    stdscr.clear()

    r = random.randrange(0,100)
    if r >= 75:
        r = True
    elif r >= 50 and r < 75:
        r = False
    elif r >= 25 and r < 50:
        r = True
    else:
        r = False

    if r:
        for d in droplets:
            current.append(d.copy())

    # stdscr.addstr(y, x, '\\')
    for i, d in enumerate(current):
        try:
            stdscr.addstr(d[1], d[0], '\\', curses.color_pair(2))
            d[1] += 1
            d[0] += 1
        except:
            if d[1] >= dim[0] or d[0] >= dim[1]:
                del current[i]

    brb = ' Zaraz Wracam '
    diff = datetime.now().replace(microsecond=0) - start
    ld = (len(brb) - len(str(diff)));

    hy = dim[0]//2;
    remaining = '%s%s%s' % (ld*' ', diff, ld*' ')

    if len(brb) > len(remaining):
        longest = len(brb)
    else:
        longest = len(remaining)

    stdscr.addstr((hy)-1, (dim[1]//2) - (longest//2), ' '*longest)
    stdscr.addstr(hy, (dim[1]//2) - (len(brb)//2), brb)

    stdscr.addstr((hy)+1, (dim[1]//2) - (len(remaining)//2), remaining)
    
    stdscr.addstr((hy)+2, (dim[1]//2) - (longest//2), ' '*longest)

    stdscr.addstr(0,0,'%d' % len(current))

    stdscr.refresh()

    sleep(0.2)

curses.nocbreak()
stdscr.keypad(False)
curses.curs_set(True)
curses.echo()
curses.endwin()
