#!/bin/bash

normal=`xrandr --verbose | sed -n 2p| grep -o normal | wc -w`
#right=`xrandr --verbose | sed -n 2p| grep -o right | wc -w`
left=`xrandr --verbose | sed -n 2p| grep -o left | wc -w`
#inverted=`xrandr --verbose | sed -n 2p| grep -o inverted | wc -w`

[ $normal -eq 2 ] && xrandr -o 1
[ $left -eq 2 ] && xrandr -o 0
