#!/bin/bash

. $HOME/.env/fun

RUNZSH=no sh <(curl -fsSL \
https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)

ZSH_CUSTOM=${ZSH_CUSTOM:-"$HOME/.oh-my-zsh/custom"}
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

sym_f $HOME/.env/.zshrc $HOME/.zshrc
sym_f $HOME/.env/.zprofile $HOME/.zprofile

exit 0
